---
- name: Specify MySQL root password before installing
  debconf: name='{{mysql_package_name}}' question='mysql-server/root_password' value='{{database_pwd | quote}}' vtype='password'
  become: true
  
- name: Confirm MySQL root password before installing
  debconf: name='{{mysql_package_name}}' question='mysql-server/root_password_again' value='{{database_pwd | quote}}' vtype='password'
  become: true

- name: Install MySQL
  apt:
    pkg:
      - mysql-server
      - python3-mysqldb
    state: present
  become: true

- name: Create my.cnf
  template: src=templates/my.cnf dest={{ ansible_env.HOME}}/.my.cnf
  become: true

- name: Remove anonymous users
  mysql_user: name="" host_all=yes state=absent
    
- name: Remove test database
  mysql_db: name=test state=absent

- name: Remove itrust database
  mysql_db: name={{itrust_db_name}} state=absent

- name: Add database user
  mysql_user: name={{database_user_name}} password={{database_pwd}} priv=*.*:ALL,GRANT state=present
   
