pipeline {
    agent any
    stages {
        stage('Setup') {
            steps {
                withCredentials([file(credentialsId: 'db_properties', variable: 'db_properties'),
                                 file(credentialsId: 'email_properties', variable: 'email_properties')]) {
                    sh 'cp -f \$db_properties iTrust2/src/main/java/db.properties'
                    sh 'cp -f \$email_properties iTrust2/src/main/java/email.properties'
                    sh 'cd iTrust2 && mvn -f pom-data.xml process-test-classes'
                }
            }
        }
        stage('Build') {
            steps{
                timeout(time: 15, unit: 'MINUTES') {
                    sh 'cd iTrust2 && mvn -f pom.xml clean test verify checkstyle:checkstyle -Dmaven.test.failure.ignore=false'
                }
            }
        }
    }
    post { 
        always {
            junit 'iTrust2/target/surefire-reports/**/*.xml'
            jacoco(
                    execPattern: 'iTrust2/target/coverage-reports/*.exec',
                    classPattern: 'iTrust2/target/classes',
                    sourcePattern: 'iTrust2/src/main/java',
                    exclusionPattern: 'iTrust2/src/test*',
                    changeBuildStatus: true,
                    minimumInstructionCoverage: '50'
                )
            sh 'cd /jenkins-server/itrust-fuzzer && sudo npm start &'
        }
    }
}
